---
## The task un-installs old utility scripts.

- name: Uninstall -> Scripts
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /usr/bin/switch-display-inputs
    - /opt/scripts/switch-display-inputs.sh
