---
## The task installs the Sublime text editor.

- name: Sublime Setup -> Add GPG apt key
  ansible.builtin.apt_key:
    url: https://download.sublimetext.com/sublimehq-pub.gpg
    state: present
    keyring: /etc/apt/trusted.gpg.d/sublime.gpg

- name: Sublime Setup -> Add apt repository
  ansible.builtin.apt_repository:
    repo: deb https://download.sublimetext.com apt/stable/
    state: present

- name: Sublime Setup -> Install sublime
  ansible.builtin.apt:
    name:
      - sublime-text
    state: latest
    update_cache: true
