---
# @file ubuntu-vscode-plugins.yml
# @brief Install VSCode plugins.
#
# @description The task installs VSCode plugins.
#
# IMPORTANT: Run in a playbook that is NOT becoming ``root``.

- name: Install -> VSCode Extensions
  ansible.builtin.shell: |
    extensions=(
      'streetsidesoftware.code-spell-checker'
      'asciidoctor.asciidoctor-vscode'
      'ms-azuretools.vscode-docker'
      'aaron-bond.better-comments'
      'pomdtr.markdown-kroki'
      'timonwong.shellcheck'
      'jebbs.plantuml'
      'github.vscode-github-actions'
      'redhat.vscode-yaml'
      'ms-vscode.makefile-tools'
      'ms-vscode-remote.remote-containers'
    )
    for extension in "${extensions[@]}"
    do
      echo "[INFO] Install VSCode extension $extension"
      code --extension "$extension"
    done
  args:
    executable: /bin/bash
