---
# @file common-install-docker-wrapper-scripts.yml
# @brief Lorem Ipsum ...
#
# @description Lorem Ipsum ...
# TODO ...

- name: Config -> Create directories for docker wrappers
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: u=rwx,g=rx,o=rx
  with_items:
    - /opt/docker-wrappers

- name: Config -> Copy docker wrapper scipts configuration
  ansible.builtin.copy:
    src: "../assets/scripts/docker/wrappers/{{ item }}.sh"
    dest: "/opt/docker-wrappers/{{ item }}.sh"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: u=rwx,g=rx,o=rx
  with_items:
    - groovy
    - hadolint
    - mvn
    - node-npm
    - shellcheck
    - yamllint

- name: Config -> Create symlinks to docker wrapper scipts in /usr/bin
  ansible.builtin.file:
    src: "/opt/docker-wrappers/{{ item }}.sh"
    dest: "/usr/bin/{{ item }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    state: link
  with_items:
    - groovy
    - hadolint
    - mvn
    - shellcheck
    - yamllint

- name: Config -> Create symlinks to docker wrapper scipt 'node-npm.sh' in /usr/bin
  ansible.builtin.file:
    src: "/opt/docker-wrappers/node-npm.sh"
    dest: "/usr/bin/{{ item }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    state: link
  with_items:
    - node
    - npm
