---
name: Auto-generate docs

on:
  push:
    # branches: [ "main", "feat/*", "release/*" ]
    branches-ignore:
      - dependabot/**

permissions:
  contents: read

jobs:
  update-antora-yml:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Print Branchname
        run: echo ${{github.ref}}
      - name: Adjust version in antora.yml
        uses: sebastian-sommerfeld-io/github-action-update-antora-yml@main
        with:
          git_ref: ${{github.ref}}
      - name: Run yamllint for docs/antora.yml
        uses: ibiqlik/action-yamllint@v3
        with:
          file_or_dir: docs/antora.yml
      - name: Commit and push
        uses: EndBug/add-and-commit@v9
        with:
          author_name: sebastian
          author_email: sebastian@sommerfeld.io
          message: "[Actions Bot] refactor: set antora version to branchname"
          add: docs/antora.yml

  README:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs: update-antora-yml

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: README.adoc
        uses: sebastian-sommerfeld-io/github-action-generate-readme@main
        with:
          caption: Configurations Startpage
      - name: Commit and push
        uses: EndBug/add-and-commit@v9
        with:
          author_name: sebastian
          author_email: sebastian@sommerfeld.io
          message: "[Actions Bot] docs: auto-generated adoc contents"
          add: README.adoc

  bash-script-docs:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs: README

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Generate docs from bash scripts
        uses: sebastian-sommerfeld-io/github-action-generate-docs@main
      - name: Commit and push
        uses: EndBug/add-and-commit@v9
        with:
          author_name: sebastian
          author_email: sebastian@sommerfeld.io
          message: "[Actions Bot] docs: auto-generated bash script documentation from *.sh files"
          add: docs/modules

  check-links-in-adoc-files:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs: bash-script-docs

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install asciidoc-link-check
        run: npm install --location=global asciidoc-link-check@1.0.15
      - name: Validate links in all adoc files
        run: find . -name '*.adoc' -exec asciidoc-link-check -c .adoc-links.json -p {} \;

  on-failure:
    runs-on: ubuntu-latest
    needs: ['README', 'update-antora-yml', 'bash-script-docs', 'check-links-in-adoc-files']
    if: failure()

    steps:
      - name: Send Pipeline Status to Google Chat
        if: always()
        uses: Co-qn/google-chat-notification@releases/v1
        with:
          name: ${{ github.workflow }}
          url: ${{ secrets.GOOGLE_CHAT_WEBHOOK }}
          status: failure
