---
name: "Global: Apply Github Configuration"

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/configure-github.yml
      - src/main/github
  schedule:
    - cron: '0 6 * * 1' # https://crontab.guru
  workflow_dispatch:

permissions:
  contents: write
  issues: write

jobs:
  lint-terraform:
    name: Lint Terraform config
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Debug
        run: pwd && ls -alF
      - name: tflint
        run: |
          (
            cd src/main/github || exit
            ./apply-config.sh lint
          )
        shell: bash

  apply-github-config:
    name: Apply config by running Terraform
    runs-on: ubuntu-latest
    needs: lint-terraform
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: initialize
        run: |
          (
            cd src/main/github || exit
            ./apply-config.sh init
          )
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: bash
      - name: Checkout code of configs-persistent-data repository
        uses: actions/checkout@v4
        with:
          repository: sebastian-sommerfeld-io/configs-persistent-data
          token: ${{ secrets.TERRAFORM }}
          path: src/main/github/tmp-repos/configs-persistent-data
      - name: validate
        run: |
          (
            cd src/main/github || exit
            ./apply-config.sh validate
          )
        shell: bash
      - name: plan
        run: |
          (
            cd src/main/github || exit
            ./apply-config.sh plan ${{ secrets.TERRAFORM }} ${{ secrets.BW_CLIENT_ID }} ${{ secrets.BW_CLIENT_SECRET }} ${{ secrets.BW_MASTER_PASS }}
          )
        shell: bash
      - name: apply
        run: |
          (
            cd src/main/github || exit
            ./apply-config.sh apply ${{ secrets.TERRAFORM }} ${{ secrets.BW_CLIENT_ID }} ${{ secrets.BW_CLIENT_SECRET }} ${{ secrets.BW_MASTER_PASS }}
          )
        shell: bash
      - name: ALWAYS cleanup
        if: always()
        run: |
          (
            cd src/main/github || exit
            ./apply-config.sh cleanup
          )
        shell: bash

  update-repo:
    name: Format and Docs
    runs-on: ubuntu-latest
    needs: apply-github-config
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: format
        run: |
          (
            cd src/main/github || exit
            ./apply-config.sh fmt
          )
        shell: bash
      - name: Copy help.adoc to Antora partial
        run: |
          TARGET_ADOC="docs/modules/ROOT/partials/GENERATED/github/config/help.adoc"

          (
              echo "// +---------------------------------------------+"
              echo "// |                                             |"
              echo "// |    DO NOT EDIT DIRECTLY !!!!!               |"
              echo "// |                                             |"
              echo "// |    See: src/main/github/assets/help.adoc    |"
              echo "// |                                             |"
              echo "// +---------------------------------------------+"
              echo
          ) > "$TARGET_ADOC"

          cat src/main/github/assets/help.adoc >> "$TARGET_ADOC"
        shell: bash
      - name: Generate docs about terraform config
        run: |
          (
            cd src/main/github || exit
            ./apply-config.sh docs
          )
      - name: Commit and push
        uses: EndBug/add-and-commit@v9
        with:
          author_name: sebastian
          author_email: sebastian@sommerfeld.io
          message: "[Actions Bot] formatted terraform files and auto-generated docs"

  on-failure:
    runs-on: ubuntu-latest
    needs: ['lint-terraform', 'apply-github-config', 'update-repo']
    if: failure()
    steps:
      - name: Send Pipeline Status to Google Chat
        if: always()
        uses: Co-qn/google-chat-notification@releases/v1
        with:
          name: ${{ github.workflow }}
          url: ${{ secrets.GOOGLE_CHAT_WEBHOOK }}
          status: failure
