---
# @file docs-as-code.yml
# @brief Github Actions workflow that generates Asciidoc documentation based on source code from this repo and updates the projects README file.
#
# @description This GitHub Actions workflow serves the purpose of generating Asciidoc documentation
# based on the source code from the repository and updating the project's ``README.adoc`` based on
# contents from the Antora docs. It is designed to automatically trigger whenever new code is pushed
# to the remote repository. Additionally, it is scheduled to run each night to ensure the
# documentation is up-to-date.
#
# By utilizing this workflow, the project ensures that the Asciidoc documentation stays in sync with
# the latest code changes. This leads to improved documentation quality and better project
# understanding.


name: Generate Docs

on:
  push:
    # branches: [ "main", "feat/*", "release/*" ]
    branches-ignore:
      - dependabot/**

permissions:
  contents: write
  security-events: write

concurrency:
  group: "docs-as-code-${{ github.event.repository.name }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  adjust-antora-yml:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        antora-yml-file: ['docs/antora.yml']
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{github.ref}}
      - name: Print Branchname
        run: echo ${{github.ref}}
        shell: bash
      - name: Adjust version in ${{ matrix.antora-yml-file }}
        uses: sebastian-sommerfeld-io/github-action-update-antora-yml@main
        with:
          git_ref: ${{github.ref}}
          file: ${{ matrix.antora-yml-file }}
      - name: Run yamllint for ${{ matrix.antora-yml-file }}
        uses: ibiqlik/action-yamllint@v3
        with:
          file_or_dir: ${{ matrix.antora-yml-file }}
      - name: Commit and push
        uses: EndBug/add-and-commit@v9
        with:
          author_name: sebastian
          author_email: sebastian@sommerfeld.io
          message: "[Actions Bot] update antora yml"

  generate-docs:
    runs-on: ubuntu-latest
    needs: ['adjust-antora-yml']
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{github.ref}}
      - name: Generate docs from source code
        run: docker run --rm --volume "$(pwd):/project" --workdir "/project" sommerfeldio/source2docs:rc
        shell: bash
      - name: README.adoc
        run: |
          TARGET_ADOC="README.adoc"
          cp docs/modules/ROOT/pages/index.adoc "$TARGET_ADOC"
          {
            echo
            echo "// +-------------------------------------------+"
            echo "// |                                           |"
            echo "// |    DO NOT EDIT DIRECTLY !!!!!             |"
            echo "// |                                           |"
            echo "// |    File is auto-generated by pipeline.    |"
            echo "// |    Contents are based on Antora docs.     |"
            echo "// |                                           |"
            echo "// +-------------------------------------------+"
          } >> "$TARGET_ADOC"
        shell: bash
      - name: LICENSE.adoc
        run: |
          TARGET_ADOC="LICENSE.adoc"
          cp docs/modules/ROOT/pages/license.adoc "$TARGET_ADOC"
          {
            echo
            echo "// +-------------------------------------------+"
            echo "// |                                           |"
            echo "// |    DO NOT EDIT DIRECTLY !!!!!             |"
            echo "// |                                           |"
            echo "// |    File is auto-generated by pipeline.    |"
            echo "// |    Contents are based on Antora docs.     |"
            echo "// |                                           |"
            echo "// +-------------------------------------------+"
          } >> "$TARGET_ADOC"
        shell: bash
      - name: Commit and push
        uses: EndBug/add-and-commit@v9
        with:
          author_name: sebastian
          author_email: sebastian@sommerfeld.io
          message: "[Actions Bot] generate docs"

  on-failure:
    runs-on: ubuntu-latest
    needs: ['adjust-antora-yml', 'generate-docs']
    if: failure()
    steps:
      - name: Send Pipeline Status to Google Chat
        if: always()
        uses: Co-qn/google-chat-notification@releases/v1
        with:
          name: ${{ github.workflow }}
          url: ${{ secrets.GOOGLE_CHAT_WEBHOOK }}
          status: failure
